import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting seed process for 30 clients...');

  // 1. Get default user
  const adminUser = await prisma.user.findFirst();
  if (!adminUser) {
    throw new Error('No user found in database.');
  }
  const userId = adminUser.id;
  console.log(`Using User ID: ${userId} (${adminUser.fullName})`);

  // 2. Ensure Hotels exist
  const hotelsData = [
    {
      name: 'Sofitel Legend Santa Clara',
      zone: 'Centro Histórico',
      sector: 'San Diego',
      contactPhone: '+57 605 650 4700',
      commissionRate: 10.00,
      userId,
      status: 'active',
    },
    {
      name: 'Hotel Charleston Santa Teresa',
      zone: 'Centro Histórico',
      sector: 'Plaza Santa Teresa',
      contactPhone: '+57 605 664 9494',
      commissionRate: 12.00,
      userId,
      status: 'active',
    },
    {
      name: 'Hyatt Regency Cartagena',
      zone: 'Bocagrande',
      sector: 'Carrera 1',
      contactPhone: '+57 605 694 1234',
      commissionRate: 10.00,
      userId,
      status: 'active',
    },
    {
      name: 'Hotel Decameron Barú',
      zone: 'Zona Insular',
      sector: 'Isla Barú',
      contactPhone: '+57 605 693 2000',
      commissionRate: 15.00,
      userId,
      status: 'active',
    },
    {
      name: 'Estelar Cartagena Hotel & Centro de Convenciones',
      zone: 'Bocagrande',
      sector: 'Calle 6',
      contactPhone: '+57 605 651 7800',
      commissionRate: 10.00,
      userId,
      status: 'active',
    },
  ];

  const createdHotels = [];
  for (const hData of hotelsData) {
    const existing = await prisma.hotel.findFirst({ where: { name: hData.name } });
    if (existing) {
      createdHotels.push(existing);
    } else {
      const h = await prisma.hotel.create({ data: hData });
      createdHotels.push(h);
    }
  }

  console.log(`Hotels ready: ${createdHotels.length} hotels available.`);

  // 3. Define 30 complete client records
  const clientsList = [
    {
      fullName: 'Carlos Eduardo Mendoza Silva',
      documentNumber: '1018239401',
      email: 'carlos.mendoza@gmail.com',
      phone: '+57 310 456 7890',
      nationality: 'Colombiana',
      numberOfPeople: 2,
      observations: 'Viaje de aniversario. Requiere bienvenida especial con champán en la habitación.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '304',
    },
    {
      fullName: 'Sofía María Rodríguez Torres',
      documentNumber: '1092837410',
      email: 'sofia.rodriguez@hotmail.com',
      phone: '+57 315 987 6543',
      nationality: 'Colombiana',
      numberOfPeople: 4,
      observations: 'Familia con 2 niños pequeños. Solicita asientos juntos en transportes y chalecos salvavidas infantiles.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '512',
    },
    {
      fullName: 'John William Smith',
      documentNumber: 'PAS-US9283741',
      email: 'john.smith@yahoo.com',
      phone: '+1 305 456 7890',
      nationality: 'Estadounidense',
      numberOfPeople: 1,
      observations: 'Viajero de negocios. Requiere facturación corporativa y atención integral en inglés.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '201',
    },
    {
      fullName: 'Ana Lucía Gómez Ramírez',
      documentNumber: '1032456789',
      email: 'ana.gomez@outlook.com',
      phone: '+57 300 234 5678',
      nationality: 'Colombiana',
      numberOfPeople: 3,
      observations: 'Alergia severa a mariscos y frutos secos. Confirmar menú alternativo en pasadías.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '1408',
    },
    {
      fullName: 'Jean-Luc Dubois',
      documentNumber: 'PAS-FR8839201',
      email: 'jeanluc.dubois@orange.fr',
      phone: '+33 612 345 678',
      nationality: 'Francesa',
      numberOfPeople: 2,
      observations: 'Interesado en fotografía de arquitectura e historia colonial. Prefiere guías especializados.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '110',
    },
    {
      fullName: 'Mariana Restrepo Jaramillo',
      documentNumber: '1045678901',
      email: 'mariana.restrepo@gmail.com',
      phone: '+57 318 765 4321',
      nationality: 'Colombiana',
      numberOfPeople: 5,
      observations: 'Grupo familiar extenso. Requiere apoyo con silla de ruedas para un adulto mayor en embarques.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[3].id,
      roomNumber: '215-B',
    },
    {
      fullName: 'Michael Patrick Brown',
      documentNumber: 'PAS-UK4928173',
      email: 'michael.brown@btinternet.com',
      phone: '+44 7911 123456',
      nationality: 'Británica',
      numberOfPeople: 2,
      observations: 'Solicita guía bilingüe privado para pasadía en las islas del Rosario.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '308',
    },
    {
      fullName: 'Valentina Fernández Castro',
      documentNumber: 'PAS-AR2039481',
      email: 'valen.fernandez@gmail.com',
      phone: '+54 9 11 4567 8901',
      nationality: 'Argentina',
      numberOfPeople: 2,
      observations: 'Primera visita a Cartagena. Desea recomendaciones sobre restaurantes y vida nocturna local.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '804',
    },
    {
      fullName: 'Diego Alejandro Morales',
      documentNumber: '1056789012',
      email: 'diego.morales@yahoo.es',
      phone: '+57 312 345 6789',
      nationality: 'Colombiana',
      numberOfPeople: 1,
      observations: 'Combinación de negocios y descanso. Salida temprano para actividades acuáticas.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '902',
    },
    {
      fullName: 'Camila Andrea Benítez Herrera',
      documentNumber: 'PAS-CL3920495',
      email: 'camila.benitez@gmail.com',
      phone: '+56 9 8765 4321',
      nationality: 'Chilena',
      numberOfPeople: 3,
      observations: 'Llegada en vuelo nocturno (11:30 PM). Coordinar recogida VIP en el aeropuerto.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '405',
    },
    {
      fullName: 'Santiago Javier Peralta Ríos',
      documentNumber: 'PAS-MX5839201',
      email: 'santiago.peralta@gmail.com',
      phone: '+52 55 1234 5678',
      nationality: 'Mexicana',
      numberOfPeople: 2,
      observations: 'Celebración de cumpleaños. Solicita pastel sorpresa durante la cena de bienvenida.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '615',
    },
    {
      fullName: 'Isabella Rossi',
      documentNumber: 'PAS-IT8392014',
      email: 'isabella.rossi@libero.it',
      phone: '+39 333 123 4567',
      nationality: 'Italiana',
      numberOfPeople: 2,
      observations: 'Vegetariana estricta. Solicita confirmación de opciones gastronómicas vegetales en los tours.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '104',
    },
    {
      fullName: 'Gabriel Antonio Silva Vargas',
      documentNumber: 'PAS-PE4928301',
      email: 'gabriel.silva@hotmail.com',
      phone: '+51 987 654 321',
      nationality: 'Peruana',
      numberOfPeople: 4,
      observations: 'Familia en vacaciones anuales. Interesados en snorkeling y actividades deportivas acuáticas.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[3].id,
      roomNumber: '108-A',
    },
    {
      fullName: 'Emily Rose Johnson',
      documentNumber: 'PAS-CA9283741',
      email: 'emily.johnson@rogers.com',
      phone: '+1 416 555 0192',
      nationality: 'Canadiense',
      numberOfPeople: 1,
      observations: 'Trabajadora remota. Requiere confirmación de zonas con Wi-Fi estable durante las excursiones.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '1205',
    },
    {
      fullName: 'Hans Dieter Mueller',
      documentNumber: 'PAS-DE4820193',
      email: 'hans.mueller@web.de',
      phone: '+49 171 1234567',
      nationality: 'Alemana',
      numberOfPeople: 2,
      observations: 'Puntualidad estricta requerida para las recogidas en el lobby del hotel.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '218',
    },
    {
      fullName: 'Lucía Mercedes Delgado',
      documentNumber: '1067890123',
      email: 'lucia.delgado@gmail.com',
      phone: '+57 320 987 6543',
      nationality: 'Colombiana',
      numberOfPeople: 3,
      observations: 'Solicita traslado privado de regreso al aeropuerto Rafael Núñez.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '708',
    },
    {
      fullName: 'Mateo Ruiz Echeverri',
      documentNumber: '1078901234',
      email: 'mateo.ruiz@gmail.com',
      phone: '+57 314 567 8901',
      nationality: 'Colombiana',
      numberOfPeople: 2,
      observations: 'Pareja joven. Interesados en tours nocturnos en chiva y fiesta en catamarán.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[3].id,
      roomNumber: '312-C',
    },
    {
      fullName: 'Daniela Patricia Vargas',
      documentNumber: 'PAS-EC3829104',
      email: 'daniela.vargas@gmail.com',
      phone: '+593 99 123 4567',
      nationality: 'Ecuatoriana',
      numberOfPeople: 2,
      observations: 'Prefiere salidas de itinerarios después de las 10:00 AM para descanso matutino.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '402',
    },
    {
      fullName: 'Andrés Felipe Castro Medina',
      documentNumber: '1089012345',
      email: 'andres.castro@outlook.com',
      phone: '+57 301 234 5678',
      nationality: 'Colombiana',
      numberOfPeople: 1,
      observations: 'Asistente a convención nacional. Tours de medio día en horarios vespertinos.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '1510',
    },
    {
      fullName: 'Natalia Santos Oliveira',
      documentNumber: 'PAS-BR4920192',
      email: 'natalia.santos@uol.com.br',
      phone: '+55 11 98765 4321',
      nationality: 'Brasileña',
      numberOfPeople: 3,
      observations: 'Prefiere atención telefónica y presencial en español o portugués.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '316',
    },
    {
      fullName: 'Fernando José Gutiérrez',
      documentNumber: 'PAS-CR2938471',
      email: 'fernando.gutierrez@gmail.com',
      phone: '+506 8888 1234',
      nationality: 'Costarricense',
      numberOfPeople: 2,
      observations: 'Aficionado a la naturaleza, ecoturismo y avistamiento de aves en el Jardín Botánico.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '1011',
    },
    {
      fullName: 'Valeria Sofía Osorio',
      documentNumber: '1090123456',
      email: 'valeria.osorio@gmail.com',
      phone: '+57 316 456 7890',
      nationality: 'Colombiana',
      numberOfPeople: 4,
      observations: 'Reserva especial de pasadía de lujo en Cholón e Isla Grande.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[3].id,
      roomNumber: '104-B',
    },
    {
      fullName: 'Alexander Novak',
      documentNumber: 'PAS-CZ3928174',
      email: 'alexander.novak@seznam.cz',
      phone: '+420 777 123 456',
      nationality: 'Checa',
      numberOfPeople: 2,
      observations: 'Requiere factura electrónica detallada a nombre de su empresa en Europa.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '1104',
    },
    {
      fullName: 'Carmen Victoria Márquez',
      documentNumber: 'PAS-VE3920194',
      email: 'carmen.marquez@gmail.com',
      phone: '+58 414 1234567',
      nationality: 'Venezolana',
      numberOfPeople: 3,
      observations: 'Viaje familiar. Solicita cuna suplementaria para infante en la habitación.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '206',
    },
    {
      fullName: 'Alejandro Martín Suárez',
      documentNumber: 'PAS-UY4920193',
      email: 'alejandro.suarez@gmail.com',
      phone: '+598 99 123 456',
      nationality: 'Uruguaya',
      numberOfPeople: 2,
      observations: 'Interesado en la historia militar colonial y recorrido guiado por el Castillo San Felipe.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '502',
    },
    {
      fullName: 'Paola Andrea Salazar',
      documentNumber: '1012345678',
      email: 'paola.salazar@gmail.com',
      phone: '+57 317 890 1234',
      nationality: 'Colombiana',
      numberOfPeople: 2,
      observations: 'Check-in tardío confirmado directamente con la recepción del hotel.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[2].id,
      roomNumber: '409',
    },
    {
      fullName: 'Kevin David Miller',
      documentNumber: 'PAS-US8392019',
      email: 'kevin.miller@gmail.com',
      phone: '+1 212 555 0148',
      nationality: 'Estadounidense',
      numberOfPeople: 2,
      observations: 'Aniversario de bodas de plata. Plan completo de experiencias gastronómicas VIP.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[1].id,
      roomNumber: '310',
    },
    {
      fullName: 'Laura Marcela Hoyos',
      documentNumber: '1023456789',
      email: 'laura.hoyos@gmail.com',
      phone: '+57 313 234 5678',
      nationality: 'Colombiana',
      numberOfPeople: 5,
      observations: 'Grupo corporativo de incentivos. Solicitan transporte ejecutivo exclusivo.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[4].id,
      roomNumber: '1602',
    },
    {
      fullName: 'Pedro Henrique Barbosa',
      documentNumber: 'PAS-BR9201948',
      email: 'pedro.barbosa@terra.com.br',
      phone: '+55 21 99876 5432',
      nationality: 'Brasileña',
      numberOfPeople: 2,
      observations: 'Solicita vehículo privado con aire acondicionado y chófer bilingüe.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[0].id,
      roomNumber: '220',
    },
    {
      fullName: 'Claudia Inés Villamizar',
      documentNumber: '1034567890',
      email: 'claudia.villamizar@gmail.com',
      phone: '+57 302 987 6543',
      nationality: 'Colombiana',
      numberOfPeople: 3,
      observations: 'Interesada en talleres de cocina caribeña y catas de café en el centro histórico.',
      status: 'active',
      createdByUserId: userId,
      hotelId: createdHotels[3].id,
      roomNumber: '201-A',
    },
  ];

  // First kill running task if needed, but here we can just execute bulk createMany
  const res = await prisma.client.createMany({
    data: clientsList,
    skipDuplicates: true,
  });

  const finalCount = await prisma.client.count();
  console.log(`\n--- SEED COMPLETE ---`);
  console.log(`Bulk inserted clients result:`, res);
  console.log(`Total clients now in DB: ${finalCount}`);
}

main()
  .catch((e) => {
    console.error('Error during client seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
